name: lichess_train

resources:
  # Use spot instances to save cost.
  accelerators: A10G
  use_spot: true


# To make this example work, please run the following command:
workdir: ~/chess_llm_interpretability


file_mounts:
  /source_files:
    source: s3://go-bucket-craft
    store: s3
    mode: MOUNT

setup: |
  set -e .
  ll
  pip install -r remote/probe_freeze.txt

run: |
  set -e
  python3 train_test_chess.py \
    --dataset_prefix random \
  python3 remote/upload_file_to_s3.py \
    --bucket_name go-bucket-craft \
    --file_paths linear_probes/tf_lens_random_8layers_ckpt_no_optimizer_chess_piece_probe_layer_0.pth linear_probes/tf_lens_random_8layers_ckpt_no_optimizer_chess_piece_probe_layer_1.pth linear_probes/tf_lens_random_8layers_ckpt_no_optimizer_chess_piece_probe_layer_2.pth linear_probes/tf_lens_random_8layers_ckpt_no_optimizer_chess_piece_probe_layer_3.pth linear_probes/tf_lens_random_8layers_ckpt_no_optimizer_chess_piece_probe_layer_4.pth linear_probes/tf_lens_random_8layers_ckpt_no_optimizer_chess_piece_probe_layer_5.pth linear_probes/tf_lens_random_8layers_ckpt_no_optimizer_chess_piece_probe_layer_6.pth linear_probes/tf_lens_random_8layers_ckpt_no_optimizer_chess_piece_probe_layer_7.pth

